// app/layout.tsx
import type { Metadata } from "next";
import { Suspense } from "react"; // <- add
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* 
          Server-rendered Suspense boundary:
          This satisfies Next 15/React 19's requirement that any client hook 
          reading URL state (useSearchParams/usePathname/useParams) sits under 
          a Suspense boundary that the server can stream.
        */}
        <Suspense fallback={null}>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
